// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: policy.proto

package policypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TickContext is everything the policy needs to make a decision for one
// tick. No state is carried across calls — the home supplies its own
// measurements and physical parameters every time.
type TickContext struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeId        string                 `protobuf:"bytes,1,opt,name=home_id,json=homeId,proto3" json:"home_id,omitempty"`
	Tick          int32                  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Hour          float64                `protobuf:"fixed64,3,opt,name=hour,proto3" json:"hour,omitempty"`
	SolarKw       float64                `protobuf:"fixed64,4,opt,name=solar_kw,json=solarKw,proto3" json:"solar_kw,omitempty"`                     // instantaneous solar output
	LoadKw        float64                `protobuf:"fixed64,5,opt,name=load_kw,json=loadKw,proto3" json:"load_kw,omitempty"`                        // instantaneous household load
	BatterySocKwh float64                `protobuf:"fixed64,6,opt,name=battery_soc_kwh,json=batterySocKwh,proto3" json:"battery_soc_kwh,omitempty"` // current battery state of charge
	GridPrice     float64                `protobuf:"fixed64,7,opt,name=grid_price,json=gridPrice,proto3" json:"grid_price,omitempty"`               // $/kWh at the grid tariff
	// Per-home physical limits so the server can serve heterogeneous fleets
	// from a single strategy implementation.
	BatteryCapacityKwh float64 `protobuf:"fixed64,8,opt,name=battery_capacity_kwh,json=batteryCapacityKwh,proto3" json:"battery_capacity_kwh,omitempty"`
	BatteryMaxKw       float64 `protobuf:"fixed64,9,opt,name=battery_max_kw,json=batteryMaxKw,proto3" json:"battery_max_kw,omitempty"` // symmetric charge/discharge limit
	SolarPeakKw        float64 `protobuf:"fixed64,10,opt,name=solar_peak_kw,json=solarPeakKw,proto3" json:"solar_peak_kw,omitempty"`   // needed by predictive forecasts
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TickContext) Reset() {
	*x = TickContext{}
	mi := &file_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TickContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TickContext) ProtoMessage() {}

func (x *TickContext) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TickContext.ProtoReflect.Descriptor instead.
func (*TickContext) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{0}
}

func (x *TickContext) GetHomeId() string {
	if x != nil {
		return x.HomeId
	}
	return ""
}

func (x *TickContext) GetTick() int32 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *TickContext) GetHour() float64 {
	if x != nil {
		return x.Hour
	}
	return 0
}

func (x *TickContext) GetSolarKw() float64 {
	if x != nil {
		return x.SolarKw
	}
	return 0
}

func (x *TickContext) GetLoadKw() float64 {
	if x != nil {
		return x.LoadKw
	}
	return 0
}

func (x *TickContext) GetBatterySocKwh() float64 {
	if x != nil {
		return x.BatterySocKwh
	}
	return 0
}

func (x *TickContext) GetGridPrice() float64 {
	if x != nil {
		return x.GridPrice
	}
	return 0
}

func (x *TickContext) GetBatteryCapacityKwh() float64 {
	if x != nil {
		return x.BatteryCapacityKwh
	}
	return 0
}

func (x *TickContext) GetBatteryMaxKw() float64 {
	if x != nil {
		return x.BatteryMaxKw
	}
	return 0
}

func (x *TickContext) GetSolarPeakKw() float64 {
	if x != nil {
		return x.SolarPeakKw
	}
	return 0
}

// DispatchDecision: positive battery_kw charges; negative discharges.
// Positive grid_kw imports; negative exports.
type DispatchDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BatteryKw     float64                `protobuf:"fixed64,1,opt,name=battery_kw,json=batteryKw,proto3" json:"battery_kw,omitempty"`
	GridKw        float64                `protobuf:"fixed64,2,opt,name=grid_kw,json=gridKw,proto3" json:"grid_kw,omitempty"`
	Strategy      string                 `protobuf:"bytes,3,opt,name=strategy,proto3" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DispatchDecision) Reset() {
	*x = DispatchDecision{}
	mi := &file_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DispatchDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DispatchDecision) ProtoMessage() {}

func (x *DispatchDecision) ProtoReflect() protoreflect.Message {
	mi := &file_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DispatchDecision.ProtoReflect.Descriptor instead.
func (*DispatchDecision) Descriptor() ([]byte, []int) {
	return file_policy_proto_rawDescGZIP(), []int{1}
}

func (x *DispatchDecision) GetBatteryKw() float64 {
	if x != nil {
		return x.BatteryKw
	}
	return 0
}

func (x *DispatchDecision) GetGridKw() float64 {
	if x != nil {
		return x.GridKw
	}
	return 0
}

func (x *DispatchDecision) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

var File_policy_proto protoreflect.FileDescriptor

const file_policy_proto_rawDesc = "" +
	"\n" +
	"\fpolicy.proto\x12\x06policy\"\xc5\x02\n" +
	"\vTickContext\x12\x17\n" +
	"\ahome_id\x18\x01 \x01(\tR\x06homeId\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x05R\x04tick\x12\x12\n" +
	"\x04hour\x18\x03 \x01(\x01R\x04hour\x12\x19\n" +
	"\bsolar_kw\x18\x04 \x01(\x01R\asolarKw\x12\x17\n" +
	"\aload_kw\x18\x05 \x01(\x01R\x06loadKw\x12&\n" +
	"\x0fbattery_soc_kwh\x18\x06 \x01(\x01R\rbatterySocKwh\x12\x1d\n" +
	"\n" +
	"grid_price\x18\a \x01(\x01R\tgridPrice\x120\n" +
	"\x14battery_capacity_kwh\x18\b \x01(\x01R\x12batteryCapacityKwh\x12$\n" +
	"\x0ebattery_max_kw\x18\t \x01(\x01R\fbatteryMaxKw\x12\"\n" +
	"\rsolar_peak_kw\x18\n" +
	" \x01(\x01R\vsolarPeakKw\"f\n" +
	"\x10DispatchDecision\x12\x1d\n" +
	"\n" +
	"battery_kw\x18\x01 \x01(\x01R\tbatteryKw\x12\x17\n" +
	"\agrid_kw\x18\x02 \x01(\x01R\x06gridKw\x12\x1a\n" +
	"\bstrategy\x18\x03 \x01(\tR\bstrategy2J\n" +
	"\rPolicyService\x129\n" +
	"\bDispatch\x12\x13.policy.TickContext\x1a\x18.policy.DispatchDecisionB6Z4github.com/amoghmanral/electrotech/internal/policypbb\x06proto3"

var (
	file_policy_proto_rawDescOnce sync.Once
	file_policy_proto_rawDescData []byte
)

func file_policy_proto_rawDescGZIP() []byte {
	file_policy_proto_rawDescOnce.Do(func() {
		file_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)))
	})
	return file_policy_proto_rawDescData
}

var file_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_policy_proto_goTypes = []any{
	(*TickContext)(nil),      // 0: policy.TickContext
	(*DispatchDecision)(nil), // 1: policy.DispatchDecision
}
var file_policy_proto_depIdxs = []int32{
	0, // 0: policy.PolicyService.Dispatch:input_type -> policy.TickContext
	1, // 1: policy.PolicyService.Dispatch:output_type -> policy.DispatchDecision
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_policy_proto_init() }
func file_policy_proto_init() {
	if File_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_proto_rawDesc), len(file_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_proto_goTypes,
		DependencyIndexes: file_policy_proto_depIdxs,
		MessageInfos:      file_policy_proto_msgTypes,
	}.Build()
	File_policy_proto = out.File
	file_policy_proto_goTypes = nil
	file_policy_proto_depIdxs = nil
}
